FROM ubuntu:12.04
MAINTAINER Ivar Gaitan <ivar.gaitan@gmail.com>

# Update OS
RUN echo "deb http://se.archive.ubuntu.com/ubuntu precise main" > /etc/apt/sources.list
RUN apt-get update 

# Set working directory.
ENV HOME /root
WORKDIR /root

